### ISSUE TITLE
IP address are valid as email domains

### ISSUE THREAD

**Issue by sbromberger** [eraviart/Converters.jl#1]
Hi,

This is a very promising package but email / domain validation is notoriously complex. As an example:

```
Convertible("root@127.0.0.1") |> input_to_email |> to_value
ERROR: Invalid domain name.
Value: root@127.0.0.1
...
```

`root@127.0.0.1` is a valid email address.

**Comment by eraviart** [comment]
I agree with you that the input_to_email validator is not fully RFC 822 compliant. But in practice it works for every real use addresses I have encountered these last years.

The xxx@127.0.0.1 email addresses are usually used for testing, not in production. And in this case one can use xxx@localhost addresses instead.

But if you know a better validation algorithm...

**Comment by sbromberger** [comment]
I don't, but 127.0.0.1 is just an example. Any IP address is valid in the domain field of an email address. These are typically used when there is no DNS available (plant, control ,and otherwise isolated networks) and /etc/hosts has not been configured.

**Comment by eraviart** [comment]
@sbromberger: You are right. I have added an option to also accept IP addresses (currently only IPv4).
